package com.zysl.aws.mapper;

import com.zysl.aws.model.db.S3File;
import com.zysl.aws.model.db.S3FileCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface S3FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s3_file
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    int countByExample(S3FileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s3_file
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    int deleteByExample(S3FileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s3_file
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s3_file
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    int insert(S3File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s3_file
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    int insertSelective(S3File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s3_file
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    List<S3File> selectByExample(S3FileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s3_file
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    S3File selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s3_file
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") S3File record, @Param("example") S3FileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s3_file
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    int updateByExample(@Param("record") S3File record, @Param("example") S3FileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s3_file
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    int updateByPrimaryKeySelective(S3File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s3_file
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    int updateByPrimaryKey(S3File record);
}