package com.zysl.aws.mapper;

import com.zysl.aws.model.db.S3Service;
import java.util.List;

public interface S3ServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s3_service
     *
     * @mbggenerated Wed Feb 12 18:15:26 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s3_service
     *
     * @mbggenerated Wed Feb 12 18:15:26 CST 2020
     */
    int insert(S3Service record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s3_service
     *
     * @mbggenerated Wed Feb 12 18:15:26 CST 2020
     */
    S3Service selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s3_service
     *
     * @mbggenerated Wed Feb 12 18:15:26 CST 2020
     */
    List<S3Service> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s3_service
     *
     * @mbggenerated Wed Feb 12 18:15:26 CST 2020
     */
    int updateByPrimaryKey(S3Service record);
}