package com.zysl.aws.model.db;

import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.util.Date;

@Setter
@Getter
public class S3File implements Serializable {
    private static final long serialVersionUID = -3299166835018374429L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_file.id
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_file.service_no
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    private String serviceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_file.file_name
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_file.content_md5
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    private String contentMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_file.folder_name
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    private String folderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_file.down_url
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    private String downUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_file.file_size
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_file.max_amount
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    private Integer maxAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_file.down_amount
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    private Integer downAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_file.validity_time
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    private Date validityTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_file.upload_time
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_file.create_time
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_file.source_file_id
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    private Long sourceFileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_file.update_time
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    private Date updateTime;


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s3_file
     *
     * @mbggenerated Sat Feb 29 14:40:10 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", serviceNo=").append(serviceNo);
        sb.append(", fileName=").append(fileName);
        sb.append(", contentMd5=").append(contentMd5);
        sb.append(", folderName=").append(folderName);
        sb.append(", downUrl=").append(downUrl);
        sb.append(", fileSize=").append(fileSize);
        sb.append(", maxAmount=").append(maxAmount);
        sb.append(", downAmount=").append(downAmount);
        sb.append(", validityTime=").append(validityTime);
        sb.append(", uploadTime=").append(uploadTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", sourceFileId=").append(sourceFileId);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}