package com.zysl.aws.model.db;

public class S3Service {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_service.id
     *
     * @mbggenerated Fri Feb 14 12:02:46 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_service.service_no
     *
     * @mbggenerated Fri Feb 14 12:02:46 CST 2020
     */
    private String serviceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_service.service_name
     *
     * @mbggenerated Fri Feb 14 12:02:46 CST 2020
     */
    private String serviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_service.accessKey
     *
     * @mbggenerated Fri Feb 14 12:02:46 CST 2020
     */
    private String accesskey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_service.secretKey
     *
     * @mbggenerated Fri Feb 14 12:02:46 CST 2020
     */
    private String secretkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s3_service.endpoint
     *
     * @mbggenerated Fri Feb 14 12:02:46 CST 2020
     */
    private String endpoint;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s3_service.id
     *
     * @return the value of s3_service.id
     *
     * @mbggenerated Fri Feb 14 12:02:46 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s3_service.id
     *
     * @param id the value for s3_service.id
     *
     * @mbggenerated Fri Feb 14 12:02:46 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s3_service.service_no
     *
     * @return the value of s3_service.service_no
     *
     * @mbggenerated Fri Feb 14 12:02:46 CST 2020
     */
    public String getServiceNo() {
        return serviceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s3_service.service_no
     *
     * @param serviceNo the value for s3_service.service_no
     *
     * @mbggenerated Fri Feb 14 12:02:46 CST 2020
     */
    public void setServiceNo(String serviceNo) {
        this.serviceNo = serviceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s3_service.service_name
     *
     * @return the value of s3_service.service_name
     *
     * @mbggenerated Fri Feb 14 12:02:46 CST 2020
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s3_service.service_name
     *
     * @param serviceName the value for s3_service.service_name
     *
     * @mbggenerated Fri Feb 14 12:02:46 CST 2020
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s3_service.accessKey
     *
     * @return the value of s3_service.accessKey
     *
     * @mbggenerated Fri Feb 14 12:02:46 CST 2020
     */
    public String getAccesskey() {
        return accesskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s3_service.accessKey
     *
     * @param accesskey the value for s3_service.accessKey
     *
     * @mbggenerated Fri Feb 14 12:02:46 CST 2020
     */
    public void setAccesskey(String accesskey) {
        this.accesskey = accesskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s3_service.secretKey
     *
     * @return the value of s3_service.secretKey
     *
     * @mbggenerated Fri Feb 14 12:02:46 CST 2020
     */
    public String getSecretkey() {
        return secretkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s3_service.secretKey
     *
     * @param secretkey the value for s3_service.secretKey
     *
     * @mbggenerated Fri Feb 14 12:02:46 CST 2020
     */
    public void setSecretkey(String secretkey) {
        this.secretkey = secretkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s3_service.endpoint
     *
     * @return the value of s3_service.endpoint
     *
     * @mbggenerated Fri Feb 14 12:02:46 CST 2020
     */
    public String getEndpoint() {
        return endpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s3_service.endpoint
     *
     * @param endpoint the value for s3_service.endpoint
     *
     * @mbggenerated Fri Feb 14 12:02:46 CST 2020
     */
    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s3_service
     *
     * @mbggenerated Fri Feb 14 12:02:46 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", serviceNo=").append(serviceNo);
        sb.append(", serviceName=").append(serviceName);
        sb.append(", accesskey=").append(accesskey);
        sb.append(", secretkey=").append(secretkey);
        sb.append(", endpoint=").append(endpoint);
        sb.append("]");
        return sb.toString();
    }
}